/* Word Coach Ultra — word bank
   Format: [word, meaning, Telugu gloss, example sentence, level 1-3]
   455+ words: everyday + academic vocabulary (economics, civics, commerce,
   accountancy, science, English, Telugu studies) with Telugu glosses. */
window.WORD_BANK = [
["brave", "showing courage; not afraid", "ధైర్యము", "The brave girl spoke in front of the whole school.", 1],
["honest", "always telling the truth", "నిజాయితీ", "An honest student returns money he finds.", 1],
["kind", "friendly and caring to others", "దయగల", "Be kind to animals and younger children.", 1],
["rapid", "very fast", "వేగవంతమైన", "The rapid train reached Hyderabad in one hour.", 1],
["silent", "making no sound", "నిశ్శబ్ద", "The library was silent during the exam.", 1],
["village", "a small group of houses in the countryside", "గ్రామం", "My grandfather lives in a village near Warangal.", 1],
["wisdom", "good judgment from knowledge and experience", "వివేకము", "The old teacher shared her wisdom with us.", 1],
["journey", "travelling from one place to another", "ప్రయాణం", "The journey from Hyderabad to Delhi takes one day.", 1],
["harvest", "gathering crops when they are ready", "పంట కొయ్యడం", "Farmers celebrate harvest time with songs.", 1],
["market", "a place where people buy and sell things", "మార్కెట్", "We buy fresh vegetables at the Sunday market.", 1],
["danger", "the possibility of harm", "ప్రమాదం", "The sign warned of danger near the deep river.", 1],
["effort", "hard work towards a goal", "కృషి", "Passing the exam needs daily effort.", 1],
["habit", "something you do regularly without thinking", "అలవాటు", "Reading one page daily is a good habit.", 1],
["insect", "a small creature with six legs", "కీటకం", "A butterfly is a beautiful insect.", 1],
["jewel", "a precious stone like a diamond or ruby", "రత్నం", "The queen wore a red jewel in her crown.", 1],
["ladder", "steps used for climbing up", "నిచ్చెన", "He climbed the ladder to pick mangoes.", 1],
["mentor", "a wise person who guides you", "మార్గదర్శి", "My mentor helps me choose good books.", 1],
["narrow", "not wide; thin", "ఇరుకైన", "The narrow lane fits only one bicycle.", 1],
["ocean", "the vast salt water covering most of Earth", "సముద్రం", "Whales live deep in the ocean.", 1],
["patient", "able to wait calmly", "సహనం", "A patient fisherman waits quietly for hours.", 1],
["polite", "having good manners", "మర్యాదగల", "A polite greeting makes teachers happy.", 1],
["reward", "something given for good work", "బహుమతి", "The reward for practice is progress.", 1],
["shelter", "a safe place to stay", "ఆశ్రయం", "During the storm, the temple gave us shelter.", 1],
["talent", "a natural skill", "ప్రతిభ", "Her talent for singing amazed everyone.", 1],
["unity", "people working together as one", "ఐక్యత", "In unity, the team won the championship.", 1],
["valley", "low land between hills or mountains", "లోయ", "The Kashmir valley is full of flowers.", 1],
["weapon", "a tool used to fight or defend", "ఆయుధం", "In the game, a sword is the hero's weapon.", 1],
["youth", "the time of being young", "యవ్వనం", "Spend your youth learning useful skills.", 1],
["zeal", "great energy and enthusiasm", "ఉత్సాహం", "She practises maths with great zeal.", 1],
["anchor", "a heavy hook that holds a ship in place", "లంగరు", "The ship dropped anchor near the port.", 1],
["border", "the line between two places or countries", "సరిహద్దు", "Wagah is a famous border ceremony place.", 1],
["candle", "wax stick that gives light when burning", "కొవ్వొత్తి", "We lit a candle when the power went off.", 1],
["donate", "to give something to help others", "విరాళమివ్వడం", "We donate old books to the village school.", 1],
["energy", "power to do work", "శక్తి", "Sleep well to save energy for the match.", 1],
["famous", "known by many people", "ప్రసిద్ధ", "Hyderabad is famous for biryani.", 1],
["gather", "to come together in a group", "గుమిగూడడం", "Students gather in the ground every morning.", 1],
["honour", "great respect earned by good actions", "గౌరవం", "Winning the medal was an honour for our school.", 1],
["island", "land surrounded by water", "దీవి", "The Andaman islands are in the Bay of Bengal.", 1],
["jungle", "a thick forest with wild animals", "అడవి", "The tiger lives deep in the jungle.", 1],
["knight", "an armoured warrior of old times", "యోధుడు", "The knight guarded the castle gate.", 1],
["abundant", "present in large quantity", "విస్తారమైన", "The region has abundant rainfall in July.", 2],
["bargain", "discussing a price to make it lower", "బేరం ఆడడం", "My mother can bargain well at the market.", 2],
["campaign", "planned activities to achieve a goal", "ప్రచారము", "The school started a clean water campaign.", 2],
["decade", "a period of ten years", "దశాబ్దం", "A decade ago, phones had no cameras.", 2],
["economy", "the system of money and trade of a country", "ఆర్థిక వ్యవస్థ", "Agriculture supports our economy.", 2],
["famine", "extreme lack of food over a wide area", "కరువు", "The famine forced families to migrate.", 2],
["genuine", "real; not fake", "నిజమైన", "The shop sells genuine leather bags.", 2],
["heritage", "valuable traditions passed down generations", "వారసత్వము", "Charminar is part of our heritage.", 2],
["inflation", "general rise in prices over time", "ద్రవ్యోల్బణం", "Inflation makes vegetables costly.", 2],
["justice", "fair treatment under the law", "న్యాయం", "The judge gave justice to the poor farmer.", 2],
["kingdom", "a land ruled by a king or queen", "రాజ్యం", "The Golconda kingdom was rich in diamonds.", 2],
["legislate", "to make laws", "చట్టం చేయడం", "Parliament can legislate for the whole country.", 2],
["merchant", "a person who buys and sells goods", "వ్యాపారి", "The merchant travelled with silk and spices.", 2],
["nominate", "to officially suggest someone for a role", "నామినేట్ చేయడం", "The class will nominate a leader tomorrow.", 2],
["obstacle", "something that blocks your way", "ఆటంకం", "Laziness is an obstacle to success.", 2],
["parliament", "the group of elected lawmakers", "పార్లమెంట్", "A new law was discussed in Parliament.", 2],
["quantity", "an amount or number of something", "పరిమాణం", "Buy a small quantity of rice first.", 2],
["revenue", "income earned, especially by government", "ఆదాయం", "Taxes are the main revenue of the state.", 2],
["scarcity", "shortage; not enough of something", "కొరత", "Water scarcity affected the crops.", 2],
["treaty", "a formal agreement between countries", "ఒప్పందం", "The two kings signed a peace treaty.", 2],
["urban", "related to a city", "పట్టణ", "Hyderabad is a large urban area.", 2],
["venture", "a risky but hopeful project", "సాహస ప్రయత్నం", "Opening a tea stall was her first venture.", 2],
["welfare", "health and happiness of people", "సంక్షేమము", "The government runs welfare schemes for farmers.", 2],
["candidate", "a person competing for a post", "అభ్యర్థి", "Each candidate gave a speech before voting.", 2],
["demand", "a strong request; need for goods", "డిమాండు", "There is high demand for mangoes in summer.", 2],
["export", "to send goods to another country", "ఎగుమతి", "India exports rice to many countries.", 2],
["import", "to bring goods from another country", "దిగుమతి", "We import crude oil for fuel.", 2],
["federal", "power shared between centre and states", "సమాఖ్య", "India has a federal system of government.", 2],
["majority", "more than half", "మెజారిటీ", "The majority of students passed the test.", 2],
["minority", "the smaller part of a group", "మైనారిటీ", "Minority rights are protected by law.", 2],
["opinion", "what a person thinks or believes", "అభిప్రాయం", "Everyone shared an opinion about the new rule.", 2],
["policy", "a plan of action by government or company", "విధానం", "The new education policy changed our exams.", 2],
["protest", "to show public disagreement", "నిరసన", "Farmers held a protest for fair prices.", 2],
["summit", "a top-level meeting of leaders", "శిఖరాగ్ర సమావేశం", "Climate was discussed at the world summit.", 2],
["budget", "a plan of income and spending", "బడ్జెట్", "Our family budget saves money each month.", 2],
["credit", "buying now and paying later; praise", "రుణము", "The bank gave credit to the young farmer.", 2],
["deposit", "money kept safely in a bank", "డిపాజిట్", "She made a deposit into her savings account.", 2],
["fund", "money collected for a purpose", "నిధి", "The class collected a fund for the picnic.", 2],
["ledger", "a book recording money in and out", "కాయితం, ఖాతా పుస్తకం", "The shopkeeper writes daily sales in a ledger.", 2],
["audit", "an official check of accounts", "తనిఖీ", "An audit found no mistakes in the office accounts.", 2],
["amendment", "a formal change to a law", "సవరణ", "The amendment improved the education act.", 3],
["arbitrary", "based on whim, not reason", "అన్యాయమైన", "An arbitrary decision confused the workers.", 3],
["bureaucracy", "a system of government offices and officials", "అధికార వర్గం", "Bureaucracy can make approvals slow.", 3],
["coalition", "parties joining to form a government", "సంకీర్ణం", "A coalition government was formed after elections.", 3],
["commerce", "buying and selling on a large scale", "వాణిజ్యం", "Chambers of commerce support trade.", 3],
["constitution", "the supreme law of a country", "రాజ్యాంగం", "Our constitution gives us fundamental rights.", 3],
["deficit", "the amount by which spending exceeds income", "లొట్టు", "The budget deficit worried the minister.", 3],
["democracy", "rule by the people through elections", "ప్రజాస్వామ్యం", "India is the world's largest democracy.", 3],
["diplomacy", "skillful handling of relations between nations", "రాజనీతి, కూతనీతి", "War was avoided through careful diplomacy.", 3],
["entrepreneur", "a person who starts and runs a business", "పారిశ్రామికవేత్త, యజమాని", "The young entrepreneur opened two shops.", 3],
["fiscal", "related to government money and taxes", "ఆర్థిక", "The fiscal year in India ends in March.", 3],
["franchise", "the right to vote; a licensed business branch", "ఓటు హక్కు", "Universal adult franchise began in 1950.", 3],
["globalisation", "worldwide connection of trade and culture", "ప్రపంచీకరణం", "Globalisation brought foreign brands to India.", 3],
["governance", "the way a state is managed and ruled", "పాలన", "Good governance builds public trust.", 3],
["impeachment", "formal charge against a top official", "మహాభియోగం", "Impeachment is a rare and serious process.", 3],
["infrastructure", "basic systems like roads, power, water", "మౌలిక సదుపాయాలు", "Better infrastructure attracts new industries.", 3],
["investment", "money put in to gain profit later", "పెట్టుబడి", "Her small investment grew into a workshop.", 3],
["judiciary", "the system of courts and judges", "న్యాయవ్యవస్థ", "An independent judiciary protects citizens.", 3],
["liability", "a legal responsibility or debt", "బాధ్యత", "The company accepted liability for the damage.", 3],
["monopoly", "single control of a market by one seller", "ఏకస్వామ్యం", "A monopoly can raise prices unfairly.", 3],
["negotiation", "discussion aimed at reaching agreement", "చర్చలు", "The negotiation ended the long dispute.", 3],
["ordinance", "a temporary law by the executive", "ఆర్డినెన్స్", "An ordinance was issued when Parliament was closed.", 3],
["privatisation", "transferring state business to private owners", "ప్రైవేటీకరణం", "Privatisation of the airline was debated.", 3],
["referendum", "a direct vote by all people on one issue", "ప్రజాభిప్రాయ సేకరణ", "The city held a referendum on the metro plan.", 3],
["subsidy", "government support that lowers a price", "రాయితీ, సబ్సిడీ", "Farmers receive a subsidy on fertilizer.", 3],
["tariff", "a tax on imported goods", "సుంకము", "A tariff on foreign steel protected local mills.", 3],
["tribunal", "a special court for specific disputes", "ట్రిబ్యునల్, ప్రత్యేక న్యాయస్థానం", "The water tribunal settled the river dispute.", 3],
["veto", "the power to reject a decision", "వీటో", "The president may use a veto on the bill.", 3],
["warrant", "a legal paper allowing arrest or search", "వారెంట్", "The police showed a warrant before searching.", 3],
["allegiance", "loyalty to a country, leader, or cause", "విధేయత", "Soldiers swear allegiance to the nation.", 3],
["consensus", "general agreement by all", "సర్వసమ్మతి", "The committee reached a consensus after hours.", 3],
["delegation", "a group representing others", "ప్రతినిధి బృందం", "A student delegation met the collector.", 3],
["embargo", "an official ban on trade", "వాణిజ్య నిషేధం", "The embargo stopped oil sales to the nation.", 3],
["fraud", "dishonest cheating for gain", "మోసం", "Bank fraud was reported to the police.", 3],
["hierarchy", "ranking from highest to lowest", "శ్రేణి వ్యవస్థ", "The office hierarchy was explained to new staff.", 3],
["ideology", "a set of political ideas", "సిద్ధాంతం", "Each party explained its ideology to voters.", 3],
["municipal", "related to a town or city government", "పురపాలక", "The municipal corporation repaired the road.", 3],
["plebiscite", "a direct vote of the people on a key question", "ప్రజాభిప్రాయ సేకరణ", "A plebiscite decided the region's future.", 3],
["ratification", "formal approval of an agreement", "సమ్మతి, అమోదం", "Ratification of the treaty took six months.", 3],
["sovereignty", "supreme independent power of a state", "సార్వభౌమత్వం", "The constitution protects national sovereignty.", 3],
["monetary", "related to money and currency", "ద్రవ్య సంబంధమైన", "The central bank controls monetary policy to check inflation.", 3],
["deflation", "a general fall in prices", "వాస్తవిక ధరల తగ్గుదల", "Deflation can hurt farmers when prices fall sharply.", 3],
["supply", "the amount of goods available to sell", "సరఫరా", "The supply of rice was enough for the whole state.", 3],
["competition", "rivalry between sellers or players", "పోటీ", "Healthy competition keeps prices fair for buyers.", 3],
["equilibrium", "a balanced state in a market", "సమతుల్యత", "Price reaches equilibrium when demand equals supply.", 3],
["consumption", "the act of using goods and services", "వినియోగం", "Higher consumption means people are buying more.", 3],
["production", "making goods to be sold", "ఉత్పత్తి", "Factory production doubled after new machines arrived.", 3],
["distribution", "sending goods to different places", "పంపిణీ", "The distribution of ration items happens every month.", 3],
["national income", "the total money earned by a country in a year", "జాతీయ ఆదాయం", "National income shows how rich a country is.", 3],
["recession", "a period when business activity falls", "మాంద్యం", "Many shops closed during the recession.", 3],
["capital", "money or assets used to start a business", "మూలధనం", "She raised capital to open her tailoring shop.", 3],
["savings", "money kept aside for the future", "పొదుపు", "Small savings today become a big fund tomorrow.", 3],
["interest", "money paid for borrowing money", "వడ్డీ", "The bank pays interest on fixed deposits.", 3],
["currency", "the money used in a country", "కరెన్సీ, ద్రవ్యం", "The rupee is the currency of India.", 3],
["exchange rate", "the value of one currency in another", "మారకపు రేటు", "The exchange rate decides how many dollars a rupee buys.", 3],
["devaluation", "official lowering of a currency's value", "విలువ తగ్గింపు", "Devaluation made exports cheaper for foreign buyers.", 3],
["surplus", "when income is more than spending", "మిగులు", "The village cooperative earned a surplus this year.", 3],
["taxation", "the system of collecting taxes", "పన్ను విధింపు", "Fair taxation funds schools and hospitals.", 3],
["dividend", "a share of profit paid to shareholders", "లాభాంశం", "The company paid a good dividend this year.", 3],
["share", "one unit of ownership in a company", "వాటా, షేరు", "She bought a share of the sugar factory.", 3],
["stock", "the total goods kept for sale; company shares", "స్టాక్, నిల్వ", "The store keeps enough stock for the festival.", 3],
["bond", "a loan document that pays interest", "బాండ్, రుణపత్రం", "Government bonds are a safe investment.", 3],
["insurance", "protection against loss for a payment", "భీమా", "Health insurance covers hospital bills.", 3],
["pension", "regular money paid after retirement", "పింఛను", "The teacher receives a monthly pension.", 3],
["microeconomics", "study of small economic units like families and firms", "సూక్ష్మ ఆర్థిక శాస్త్రం", "Microeconomics studies how a household spends its money.", 3],
["macroeconomics", "study of the whole economy of a country", "స్థూల ఆర్థిక శాస్త్రం", "Macroeconomics examines inflation and national income.", 3],
["elasticity", "how much demand changes when price changes", "స్థితిస్థాపకత", "The elasticity of demand for salt is very low.", 3],
["globalization", "the growing connection of world economies", "ప్రపంచీకరణ", "Globalization lets Indian goods reach world markets.", 3],
["liberalization", "opening the economy to free trade and business", "సరళీకరణ", "Liberalization brought new investment into India.", 3],
["privatization", "selling government businesses to private owners", "ప్రైవేటీకరణ", "Privatization of the airline changed how it was run.", 3],
["wholesale", "selling goods in large quantities", "సగటు వర్తకం, టోకు", "He buys vegetables wholesale from the market.", 3],
["retail", "selling goods directly to customers in small amounts", "చిల్లర వ్యాపారం", "Retail shops sell rice in small packets.", 3],
["barter", "exchange of goods without money", "వస్తు మార్పిడి", "In barter, a farmer gives grain for cloth.", 3],
["debt", "money that is owed", "అప్పు, ఋణం", "The family cleared its debt after the harvest.", 3],
["liquidity", "how easily assets can be turned into cash", "ద్రవ్యత, నగదు మార్పిడి సౌలభ్యం", "Cash has high liquidity; land has low liquidity.", 3],
["depreciation", "the fall in value of an asset over time", "తరుగుదల", "Depreciation of machines is shown in accounts.", 3],
["trade", "the exchange of goods and services", "వ్యాపారం", "India's trade with other countries is growing.", 3],
["business", "an activity of making, buying or selling for profit", "వ్యాపారం, వ్యాపార సంస్థ", "Her tailoring business supports the whole family.", 3],
["price", "the amount of money asked for something", "వెల, ధర", "The price of tomatoes rose after the rain.", 2],
["profit", "money gained after expenses are paid", "లాభం", "The stall made a small profit on the first day.", 2],
["loss", "money lost when expenses exceed income", "నష్టం", "Heavy rain caused a loss to the fruit seller.", 2],
["value", "the worth of something", "విలువ, విలువైనది", "The value of honesty cannot be measured.", 2],
["preamble", "the introduction to the constitution", "ఉపోద్ఘాతం, ప్రవేశిక", "The preamble begins with 'We, the People of India'.", 3],
["fundamental rights", "basic rights guaranteed to every citizen", "ప్రాథమిక హక్కులు", "Freedom of speech is one of the fundamental rights.", 3],
["legislature", "the part of government that makes laws", "శాసనసభ", "The state legislature meets for the budget session.", 3],
["executive", "the part of government that runs the country", "కార్యనిర్వాహక వర్గం", "The executive implements the laws passed by the legislature.", 3],
["republic", "a country with an elected head of state", "గణతంత్రం", "India became a republic on 26 January 1950.", 3],
["federation", "a union of states with a central government", "సమాఖ్య", "India is a federation of states.", 3],
["election", "the process of choosing leaders by voting", "ఎన్నికలు, ఎన్నిక", "The election is held every five years.", 3],
["ballot", "a paper or system used for voting", "ఓటు పత్రం", "Voters mark their choice on the ballot.", 3],
["constituency", "an area that elects one representative", "నియోజక వర్గం", "The town forms one assembly constituency.", 3],
["political party", "a group that contests elections and forms government", "రాజకీయ పార్టీ", "The party held rallies across the district.", 3],
["opposition", "the party that opposes the ruling party", "ప్రతిపక్షం", "The opposition asked questions about the budget.", 3],
["bill", "a draft of a proposed law", "బిల్లు, ముసాయిదా చట్టం", "The bill was passed after long debate.", 3],
["act", "a law passed by the legislature", "చట్టం", "The Right to Education Act made school free.", 3],
["citizen", "a legal member of a country", "పౌరుడు", "Every citizen has duties along with rights.", 3],
["citizenship", "the legal status of being a citizen", "పౌరసత్వం", "Citizenship can be acquired by birth or by registration.", 3],
["secularism", "equal treatment of all religions by the state", "మతనిరపేక్షత", "Secularism means the state favours no religion.", 3],
["socialism", "a system that reduces inequality through public ownership", "సామ్యవాదం", "Socialism aims at fair distribution of wealth.", 3],
["liberty", "the freedom to act and think", "స్వేచ్ఛ", "Liberty is protected by the constitution.", 3],
["equality", "the state of being equal in rights", "సమానత్వం", "Equality before law applies to rich and poor alike.", 3],
["fraternity", "a feeling of brotherhood among citizens", "సోదరభావం", "Fraternity binds the people of the nation.", 3],
["civil service", "the body of officials serving the government", "పౌర సేవలు, సివిల్ సర్వీస్", "She joined the civil service after clearing the exam.", 3],
["transparency", "openness in government work", "పారదర్శకత", "Transparency reduces corruption in offices.", 3],
["accountability", "the duty to answer for one's actions", "జవాబుదారీతనం", "Accountability makes public servants careful.", 3],
["human rights", "basic rights every person has", "మానవ హక్కులు", "Human rights protect the dignity of every person.", 3],
["panchayat", "a village self-government body", "పంచాయతీ", "The panchayat maintains village roads and water.", 3],
["municipality", "a town's local government body", "మునిసిపాలిటీ", "The municipality collects property tax in towns.", 3],
["governor", "the head of a state appointed by the president", "గవర్నరు, రాష్ట్రపాలకుడు", "The governor administers the oath to ministers.", 3],
["legislative assembly", "the elected law-making house of a state", "శాసనసభ", "The legislative assembly passed the new education policy.", 3],
["president", "the head of state of a republic", "రాష్ట్రపతి", "The president is the first citizen of India.", 3],
["prime minister", "the head of the government", "ప్రధానమంత్రి", "The prime minister leads the council of ministers.", 3],
["fundamental duties", "basic duties of every citizen listed in the constitution", "ప్రాథమిక కర్తవ్యాలు", "Paying respect to the national flag is a fundamental duty.", 3],
["corruption", "dishonest use of power for money", "అవినీతి, లంచగొండితనం", "Corruption harms the poorest people most.", 3],
["defence", "protection of a country from attack", "రక్షణ", "The army is responsible for national defence.", 3],
["foreign policy", "a country's policy towards other nations", "విదేశీ విధానం", "India's foreign policy promotes peace and friendship.", 3],
["accounting", "the system of recording money transactions", "లెక్కల వ్యవస్థ, అకౌంటింగ్", "Accounting helps a business know its profit.", 3],
["journal", "the book where transactions are first recorded", "జర్నల్, దినచర్య పుస్తకం", "Each transaction is first written in the journal.", 3],
["trial balance", "a statement checking that debits equal credits", "ట్రయల్ బ్యాలెన్స్", "The trial balance matched after all entries were posted.", 3],
["balance sheet", "a statement of assets and liabilities", "బ్యాలెన్స్ షీట్, పత్రం", "The balance sheet showed the company's health.", 3],
["asset", "something of value owned by a person or firm", "ఆస్తి", "Land and machines are fixed assets of the farm.", 3],
["equity", "ownership value in a business", "వాటాదారుల మూలధనం", "Equity grows when the business earns profit.", 3],
["invoice", "a bill listing goods sold and their prices", "ఇన్వాయిస్, వస్తు పట్టిక పత్రం", "The supplier sent an invoice with the delivery.", 3],
["receipt", "a written proof of payment received", "రసీదు, చెల్లింపు రుజువు", "Keep the receipt to exchange the item later.", 3],
["expenditure", "money spent", "వ్యయం, ఖర్చు", "School expenditure includes books and repairs.", 3],
["inventory", "the complete list of goods in stock", "జాబితా, నిల్వ పట్టిక", "The shop takes inventory every Sunday.", 3],
["turnover", "the total value of sales in a period", "మొత్తం అమ్మకాలు, టర్నోవర్", "The small bakery has a daily turnover of five thousand rupees.", 3],
["margin", "the difference between cost and selling price", "లాభాంతరం, మార్జిన్", "A thin margin means less profit per item.", 3],
["markup", "the amount added to cost to fix the price", "లాభం కలిపిన ధర పెంపు", "The shop uses a ten percent markup on goods.", 3],
["discount", "a reduction from the usual price", "రాయితీ, తగ్గింపు", "Students get a discount on books.", 3],
["commission", "a payment based on the value of a sale", "కమీషను, దలాలీ", "The agent earns a five percent commission.", 3],
["partnership", "a business owned by two or more people", "భాగస్వామ్య వ్యాపారం", "The brothers run the mill in partnership.", 3],
["sole proprietorship", "a business owned by one person", "ఏకైక యాజమాన్యం", "A sole proprietorship needs no partner.", 3],
["company", "a business organization registered by law", "సంస్థ, కంపెనీ", "The company employs two hundred workers.", 3],
["corporation", "a large company treated as a legal person", "సంస్థ, నిగమం", "The corporation builds houses for the city.", 3],
["shareholder", "a person who owns shares in a company", "వాటాదారు", "Shareholders receive a part of the profits.", 3],
["director", "a member of the board that manages a company", "డైరెక్టర్, నిర్వాహకుడు", "The board of directors approved the new factory.", 3],
["management", "the people who run an organization", "నిర్వహణ", "Good management keeps workers happy.", 3],
["marketing", "the work of promoting and selling products", "మార్కెటింగ్, అమ్మకాల ప్రచారం", "Marketing campaigns bring new customers.", 3],
["advertising", "public announcements to sell products", "ప్రకటనలు, ప్రచారం", "Advertising on radio reached every village.", 3],
["brand", "a name that identifies a product", "బ్రాండ్, గుర్తింపు పేరు", "Trust in a brand grows with quality.", 3],
["consumer", "a person who buys goods for use", "వినియోగదారుడు", "The consumer has the right to safe products.", 3],
["customer", "a person who buys from a shop", "కొనుగోలుదారు, వినియోగదారు", "The customer asked for a fresh batch of bread.", 3],
["wholesaler", "a trader who sells in bulk to retailers", "టోకు వ్యాపారి", "The wholesaler supplies goods to many shops.", 3],
["retailer", "a trader who sells directly to customers", "చిల్లర వ్యాపారి", "The retailer keeps small packets for daily buyers.", 3],
["supply chain", "the full path of goods from maker to buyer", "సరఫరా గొలుసు", "A strong supply chain keeps prices stable.", 3],
["logistics", "the planning of moving goods and people", "రవాణా నిర్వహణ, లాజిస్టిక్స్", "Good logistics deliver goods on time.", 3],
["procurement", "the act of buying supplies", "కొనుగోలు, సేకరణ", "Procurement of cotton happens at harvest time.", 3],
["bankruptcy", "the legal state of being unable to pay debts", "దివాలా", "The old mill went into bankruptcy.", 3],
["insolvency", "the state of owing more than one can pay", "దివాలా తీయడం, చెల్లింపు అసమర్థత", "Insolvency forced the trader to sell his shop.", 3],
["solvency", "the ability to pay all debts", "చెల్లింపు సామర్థ్యం", "Regular savings keep a business solvent.", 3],
["goodwill", "the reputation value of a business", "మంచి పేరు విలువ, గుడ్విల్", "The shop's goodwill was built over forty years.", 3],
["accrual", "recording income or expense when earned, not when paid", "చేరిక లెక్క, అక్రూవల్", "Accrual accounting records rent even before it is paid.", 3],
["voucher", "a document supporting a payment entry", "వోచర్, చెల్లింపు రుజువు పత్రం", "Every payment needs a voucher.", 3],
["salary", "fixed pay given monthly for work", "జీతం", "The teacher's salary is credited on the first of the month.", 3],
["wages", "daily or weekly pay for work", "కూలీ", "The workers receive their wages every Saturday.", 3],
["entrepreneurship", "the skill of starting and running businesses", "వ్యాపార నైపుణ్యం, వ్యవస్థాపకత", "Entrepreneurship creates jobs for others.", 3],
["metaphor", "a comparison that says one thing IS another", "రూపకం, ఉపమానం", "'Time is a thief' is a metaphor.", 3],
["simile", "a comparison using like or as", "ఉపమానం", "'Brave as a lion' is a simile.", 3],
["alliteration", "repetition of the same starting sound", "అనుప్రాసం", "'Peter picked peppers' uses alliteration.", 3],
["hyperbole", "a great exaggeration", "అతిశయోక్తి", "'I have told you a million times' is hyperbole.", 3],
["irony", "saying the opposite of what is meant", "వ్యంగ్యం, విపర్యాసం", "Rain on the wedding day was an irony they joked about.", 3],
["satire", "humour that criticizes foolishness", "వ్యంగ్య రచన", "The cartoon was a satire on city traffic.", 3],
["allegory", "a story with a hidden moral meaning", "రూపక కథ", "The novel is an allegory of freedom.", 3],
["protagonist", "the main character of a story", "కథానాయకుడు", "The protagonist overcomes every obstacle.", 3],
["antagonist", "the character who opposes the hero", "ప్రతినాయకుడు", "The antagonist created trouble at every turn.", 3],
["narrative", "a story or account of events", "కథనం", "Her narrative of the journey was vivid.", 3],
["plot", "the sequence of events in a story", "కథాంశం", "The plot twists keep readers awake.", 3],
["setting", "the time and place of a story", "నేపథ్యం, కథా స్థలం", "The setting is a village in Telangana.", 3],
["theme", "the central idea of a work", "ఇతివృత్తం, మూలాశయం", "Hard work is the theme of the film.", 3],
["dialogue", "conversation between characters", "సంభాషణ", "The dialogue between the two friends felt real.", 3],
["monologue", "a long speech by one person", "ఏకపాత్రాభినయం, ఏకభాషణం", "The actor delivered a moving monologue.", 3],
["stanza", "a group of lines in a poem", "పద్య పాద సమూహం, స్టాంజా", "Each stanza of the poem has four lines.", 3],
["rhyme", "the repetition of similar sounds in words", "ప్రాస", "'Moon' and 'June' make a rhyme.", 3],
["rhythm", "the beat or flow of words", "లయ, తాళం", "The song's rhythm makes it easy to dance to.", 3],
["poetry", "writing that expresses feelings in verse", "కవిత్వం, పద్యం", "She writes poetry about village life.", 3],
["prose", "ordinary written language without verse", "గద్యం", "Newspaper articles are written in prose.", 3],
["essay", "a short piece of writing on one subject", "వ్యాసం", "The teacher asked for an essay on rivers.", 3],
["paragraph", "a group of sentences on one idea", "పేరా, పరిచ్ఛేదం", "Start a new paragraph for each new idea.", 3],
["composition", "the art of writing; a written piece", "కూర్పు, రచన", "His composition won the school prize.", 3],
["grammar", "the rules of a language", "వ్యాకరణం", "Good grammar makes writing clear.", 3],
["syntax", "the arrangement of words in sentences", "వాక్య నిర్మాణం, పద క్రమం", "English syntax usually follows subject-verb-object.", 3],
["vocabulary", "the words a person knows", "పదజాలం", "Reading daily grows your vocabulary.", 2],
["comprehension", "the ability to understand what is read", "గ్రహణ శక్తి, అవగాహన", "The passage tests reading comprehension.", 3],
["inference", "a conclusion drawn from evidence", "అనుమానం కాదు; ఊహాజనిత నిర్ధారణ, అనుమితి", "From the smoke we made the inference that a fire had started.", 3],
["conclusion", "the final decision or end", "తీర్మానం, ముగింపు", "The conclusion of the experiment surprised everyone.", 3],
["evidence", "facts that prove something", "సాక్ష్యం, ఆధారం", "The diary was evidence of the plan.", 3],
["argument", "a reason given for or against something", "వాదన", "Her argument convinced the whole class.", 3],
["persuasion", "the skill of convincing others", "ఒప్పించడం, ప్రేరేపణ", "Persuasion works better than force.", 3],
["rhetoric", "the art of speaking or writing effectively", "వాక్చాతుర్యం", "The leader's rhetoric moved the crowd.", 3],
["fallacy", "a false or mistaken belief", "భ్రమ, తప్పు తర్కం", "Thinking money brings happiness is a fallacy.", 3],
["bias", "an unfair preference", "పక్షపాతం", "A judge must have no bias.", 3],
["objective", "based on facts, not feelings", "నిష్పాక్షికమైన", "News should be objective and truthful.", 3],
["subjective", "based on personal feelings", "ఆత్మాశ్రయమైన, వ్యక్తిగతమైన", "Taste in music is subjective.", 3],
["summarize", "to give the main points briefly", "సంగ్రహించు, క్లుప్తీకరించు", "Summarize the chapter in five lines.", 3],
["paraphrase", "to rewrite something in your own words", "భావాన్ని మార్చకుండా వేరే మాటల్లో రాయడం", "Paraphrase the poem without changing its meaning.", 3],
["quote", "to repeat the exact words of someone", "ఉల్లేఖించు, కోట్ చేయు", "She quoted the poet in her answer.", 3],
["citation", "a reference to a source", "ఉల్లేఖనం, మూల సూచన", "Every fact needs a citation in the essay.", 3],
["bibliography", "the list of books used in writing", "గ్రంథ సూచిక", "The bibliography is at the end of the book.", 3],
["thesis", "a long essay written for a degree; a main idea", "పరిశోధన వ్యాసం, ప్రతిపాదన", "Her thesis examined village markets.", 3],
["hypothesis", "an idea to be tested", "పరికల్పన", "The experiment tested the hypothesis about plant growth.", 3],
["analysis", "careful examination of parts", "విశ్లేషణ", "The analysis of the data took a week.", 3],
["synthesis", "combining parts into a whole", "సంశ్లేషణ, సమ్మేళనం", "The essay is a synthesis of many ideas.", 3],
["evaluation", "judging the value of something", "మూల్యాంకనం", "Evaluation of the answers was fair.", 3],
["criticism", "the act of judging or finding fault", "విమర్శ", "Constructive criticism improves writing.", 3],
["interpretation", "explaining the meaning of something", "వ్యాఖ్యానం, భావార్థం", "His interpretation of the poem was fresh.", 3],
["context", "the surrounding words or situation", "సందర్భం", "The meaning of a word depends on its context.", 3],
["connotation", "the feeling a word carries beyond its meaning", "ధ్వన్యర్థం, భావార్థం", "'Home' has a warm connotation.", 3],
["denotation", "the direct dictionary meaning of a word", "శబ్దార్థం, అక్షరార్థం", "The denotation of 'rose' is the flower.", 3],
["synonym", "a word with the same meaning", "పర్యాయపదం", "'Happy' and 'joyful' are synonyms.", 2],
["antonym", "a word with the opposite meaning", "వ్యతిరేక పదం", "'Hot' and 'cold' are antonyms.", 2],
["homonym", "words that sound alike but differ in meaning", "సమాన ధ్వని గల పదాలు, హోమోనిమ్", "'Bank' of a river and a 'bank' for money are homonyms.", 3],
["prefix", "letters added before a word to change its meaning", "ఉపసర్గ", "The prefix 'un' changes 'happy' to 'unhappy'.", 3],
["suffix", "letters added at the end of a word", "ప్రత్యయం", "The suffix 'ful' turns 'care' into 'careful'.", 3],
["idiom", "a phrase whose meaning is not literal", "జాతీయం, నుడికారం", "'Break the ice' is an idiom meaning to start talking.", 3],
["proverb", "a short wise saying", "సామెత", "'Slow and steady wins the race' is a proverb.", 3],
["acronym", "a word formed from the first letters of a name", "సంక్షిప్త పదం", "'LASER' is an acronym from longer words.", 3],
["pronunciation", "the way a word is spoken", "ఉచ్చారణ", "Practice the pronunciation of 'comfortable'.", 2],
["fluency", "the ability to speak smoothly", "నిష్ణాతత్వం, సరళ ప్రసంగం", "Daily reading builds fluency in English.", 3],
["literacy", "the ability to read and write", "అక్షరాస్యత", "Literacy rates in the district are rising.", 3],
["manuscript", "a handwritten or typed original document", "హస్తప్రతి", "The old manuscript is kept in the library.", 3],
["draft", "a first version of writing", "చిత్తుప్రతి, ముసాయిదా", "Write a draft before the final essay.", 3],
["revise", "to read again and improve", "సవరించు, సరిచూచు", "Revise your notes before the exam.", 2],
["edit", "to correct and prepare writing", "సంపాదించు, సరిచేయు", "The editor will edit the article today.", 3],
["publish", "to print and release a book or article", "ప్రచురించు", "The magazine will publish her story.", 3],
["genre", "a type or category of art or writing", "శైలి, ప్రక్రియ", "Science fiction is his favourite genre.", 3],
["fiction", "stories from imagination", "కల్పిత కథలు, ఫిక్షన్", "She loves reading fiction at night.", 2],
["nonfiction", "writing about real facts", "వాస్తవ రచన, నాన్ ఫిక్షన్", "Biographies are a form of nonfiction.", 3],
["biography", "the story of a real person's life", "జీవిత చరిత్ర", "The biography of the freedom fighter inspired us.", 3],
["autobiography", "a life story written by the person themselves", "ఆత్మకథ", "Gandhiji's autobiography is called 'My Experiments with Truth'.", 3],
["editorial", "an article giving a newspaper's opinion", "సంపాదకీయం", "The editorial praised the new education policy.", 3],
["caption", "a line explaining a picture", "శీర్షిక, వివరణ వాక్యం", "The caption under the photo gave its history.", 3],
["headline", "the title of a news story", "ముఖ్య శీర్షిక", "The headline announced the election results.", 3],
["index", "a list of topics at the end of a book", "సూచిక, అనుక్రమణిక", "Check the index for page numbers.", 3],
["preface", "an introduction written by the author", "ముందుమాట", "The preface explains why the book was written.", 3],
["appendix", "extra information at the end of a book", "అనుబంధం", "The appendix has maps and tables.", 3],
["glossary", "a list of difficult words with meanings", "పదకోశం, పారిభాషిక పదాల జాబితా", "The glossary explains technical words.", 3],
["biology", "the science of living things", "జీవశాస్త్రం", "Biology studies plants, animals and humans.", 3],
["botany", "the science of plants", "వృక్షశాస్త్రం", "Botany classes grow a school garden.", 3],
["zoology", "the science of animals", "జంతుశాస్త్రం", "Zoology teaches us about animal behaviour.", 3],
["physics", "the science of matter and energy", "భౌతిక శాస్త్రం", "Physics explains why a ball falls.", 3],
["chemistry", "the science of substances and their changes", "రసాయన శాస్త్రం", "Chemistry experiments must be done carefully.", 3],
["gravity", "the force that pulls things to Earth", "గురుత్వాకర్షణ", "Gravity keeps the moon in its orbit.", 3],
["matter", "anything that has mass and occupies space", "పదార్థం", "Air is matter even though we cannot see it.", 3],
["atom", "the smallest unit of an element", "పరమాణువు", "An atom has protons and electrons.", 3],
["molecule", "two or more atoms joined together", "అణువు", "A water molecule has two hydrogen atoms.", 3],
["cell", "the basic unit of life", "కణం, జీవకణం", "Every living thing is made of cells.", 3],
["tissue", "a group of similar cells doing one job", "కణజాలం", "Muscle tissue helps the body move.", 3],
["organ", "a body part with a special function", "అవయవం", "The heart is a vital organ.", 3],
["organism", "a living being", "జీవి", "A bacterium is a tiny organism.", 3],
["species", "a group of similar living things", "జాతి", "The tiger is an endangered species.", 3],
["habitat", "the natural home of a plant or animal", "నివాస స్థలం, ఆవాసం", "The forest is the habitat of many birds.", 3],
["ecosystem", "living things and their environment together", "పర్యావరణ వ్యవస్థ", "A pond is a small ecosystem.", 3],
["environment", "everything around us; nature", "పర్యావరణం", "We must keep the environment clean.", 2],
["pollution", "harmful substances in air, water or soil", "కాలుష్యం", "Vehicle smoke causes air pollution.", 2],
["conservation", "the protection of nature and resources", "పరిరక్షణ", "Water conservation helps in summer.", 3],
["photosynthesis", "the process by which plants make food", "కిరణజన్య సంయోగక్రియ", "Photosynthesis needs sunlight, water and air.", 3],
["respiration", "the process of breathing for energy", "శ్వాసక్రియ", "Respiration releases energy from food.", 3],
["digestion", "the breaking down of food in the body", "జీర్ణక్రియ", "Digestion begins in the mouth.", 3],
["circulation", "the movement of blood through the body", "రక్త ప్రసరణ", "Exercise improves blood circulation.", 3],
["skeleton", "the framework of bones in the body", "అస్థిపంజరం", "The human skeleton has 206 bones.", 3],
["muscle", "body tissue that contracts to move parts", "కండరం", "Regular exercise builds muscle.", 3],
["nerve", "a fibre that carries messages in the body", "నరం", "The nerve carries the signal to the brain.", 3],
["gene", "the unit of heredity in cells", "జన్యువు", "Eye colour is decided by genes.", 3],
["heredity", "the passing of traits from parents to children", "వంశపారంపర్యత, వారసత్వం", "Heredity explains why children look like parents.", 3],
["evolution", "the slow change of species over time", "పరిణామం", "Evolution takes thousands of years.", 3],
["fossil", "the preserved remains of an ancient creature", "శిలాజం", "The fossil of a dinosaur was found in the hills.", 3],
["climate", "the usual weather of a place over years", "వాతావరణం, శీతోష్ణస్థితి", "The climate of Kerala is hot and wet.", 2],
["temperature", "how hot or cold something is", "ఉష్ణోగ్రత", "The temperature crossed forty degrees.", 2],
["pressure", "force pressing on a surface", "పీడనం, ఒత్తిడి", "Air pressure falls before rain.", 3],
["density", "how tightly matter is packed", "సాంద్రత", "Iron has more density than wood.", 3],
["volume", "the space something takes up", "ఘనపరిమాణం", "Measure the volume of water in the jar.", 3],
["mass", "the amount of matter in an object", "ద్రవ్యరాశి", "Mass does not change with gravity.", 3],
["velocity", "speed in a particular direction", "వేగం (దిశతో కూడిన)", "The rocket reached great velocity.", 3],
["acceleration", "the rate of change of velocity", "త్వరణం", "The cycle's acceleration slowed on the slope.", 3],
["friction", "the force that slows moving things", "రాపిడి, ఘర్షణ", "Friction wears out shoe soles.", 3],
["force", "a push or pull on an object", "బలం", "Force is needed to move a heavy box.", 2],
["magnet", "a metal that attracts iron", "అయస్కాంతం", "The magnet picked up the iron pins.", 2],
["electricity", "energy from moving charges", "విద్యుత్తు", "Electricity lights our homes.", 2],
["circuit", "the path through which electric current flows", "వలయం, సర్క్యూట్", "A broken wire breaks the circuit.", 3],
["conductor", "a material that lets electricity or heat pass", "వాహకం", "Copper is a good conductor of electricity.", 3],
["insulator", "a material that blocks electricity or heat", "అవాహకం, బంధకం", "Rubber is an insulator for electric wires.", 3],
["solution", "a mixture where one substance dissolves in another", "ద్రావణం", "Salt water is a solution of salt in water.", 3],
["mixture", "two or more substances combined", "మిశ్రమం", "Sand and salt form a mixture.", 3],
["compound", "a substance made of two or more elements", "సమ్మేళనం, సంయుక్త పదార్థం", "Water is a compound of hydrogen and oxygen.", 3],
["element", "a pure substance that cannot be split further", "మూలకం", "Oxygen is an element found in air.", 3],
["acid", "a sour substance that reacts with bases", "ఆమ్లం", "Lemon juice contains citric acid.", 3],
["base", "a substance that neutralizes acids", "క్షారం", "Soap is a mild base.", 3],
["reaction", "a change when substances meet", "చర్య, ప్రతిచర్య", "The reaction between vinegar and soda makes bubbles.", 3],
["catalyst", "a substance that speeds a reaction without changing itself", "ఉత్ప్రేరకం", "Enzymes act as catalysts in the body.", 3],
["enzyme", "a protein that speeds up body reactions", "ఎంజైమ్, జీవ ఉత్ప్రేరకం", "Saliva contains an enzyme that digests starch.", 3],
["vaccine", "a medicine that trains the body to fight disease", "టీకా", "The polio vaccine protects children.", 3],
["immunity", "the body's power to resist disease", "రోగ నిరోధక శక్తి", "Good food builds immunity.", 3],
["antibiotic", "a medicine that kills bacteria", "యాంటీబయాటిక్", "Take the full course of antibiotics.", 3],
["nutrition", "the food needed for health", "పోషణ", "Green vegetables give good nutrition.", 3],
["vitamin", "a nutrient needed in small amounts for health", "విటమిన్", "Oranges are rich in vitamin C.", 2],
["mineral", "a natural substance needed by the body", "ఖనిజం, గనిజ పదార్థం", "Iron is an important mineral in our diet.", 3],
["protein", "a nutrient that builds the body", "ప్రోటీన్, మాంసకృత్తి", "Dal and eggs are rich in protein.", 2],
["carbohydrate", "a nutrient that gives energy", "కార్బోహైడ్రేట్, పిండిపదార్థం", "Rice is full of carbohydrates.", 3],
["metabolism", "the chemical processes that keep the body alive", "జీవక్రియ", "Exercise speeds up metabolism.", 3],
["germination", "the sprouting of a seed", "మొలకెత్తడం, అంకురోత్పత్తి", "Water and warmth start germination.", 3],
["pollination", "the transfer of pollen between flowers", "పరాగసంపర్కం", "Bees help in pollination.", 3],
["fertilizer", "a substance that makes soil richer for plants", "ఎరువు, ఎరువులు", "The farmer used compost as fertilizer.", 3],
["pesticide", "a chemical that kills pests", "పురుగుమందు, క్రిమిసంహారకం", "Use pesticide only in the right amount.", 3],
["irrigation", "supplying water to crops", "నీటిపారుదల", "Canals provide irrigation to the fields.", 3],
["monsoon", "the rainy season", "రుతుపవనాలు, వర్షాకాలం", "The monsoon brings most of our rain.", 3],
["drought", "a long period with no rain", "కరవు, కరువు", "The drought dried up the village tank.", 3],
["flood", "overflow of water over dry land", "వరద, వెల్లువ", "The flood damaged the bridges.", 2],
["earthquake", "a shaking of the ground", "భూకంపం", "The earthquake shook the buildings.", 2],
["cyclone", "a violent storm with strong winds", "తుఫాను, చుడి గాలి", "The cyclone warning saved many lives.", 3],
["kavitvam", "poetry; the art of composing verse", "కవిత్వం", "Kavitvam is a core part of Telugu studies.", 3],
["padyam", "verse or poem in Telugu literature", "పద్యం", "The student recited a padyam by Vemana.", 3],
["gadya", "prose writing", "గద్యం", "The essay is written in gadya form.", 3],
["alankaram", "figure of speech that decorates poetry", "అలంకారం", "Upama is one kind of alankaram.", 3],
["rasam", "the aesthetic flavour a poem creates", "రసం", "Karuna rasam is the mood of compassion.", 3],
["chandassu", "the metre or rhythm of Telugu verse", "ఛందస్సు", "Chandassu gives a poem its musical beat.", 3],
["vyakarana", "grammar of a language", "వ్యాకరణం", "Telugu vyakarana explains word forms.", 3],
["nannaya", "the first Telugu poet, known as Aadi Kavi", "నన్నయ", "Nannaya began the Telugu Mahabharata.", 3],
["tikkana", "the Telugu poet who completed the Mahabharata", "తిక్కన", "Tikkana's poetry is famous for its grace.", 3],
["errana", "the Telugu poet who finished the third part of the Mahabharata", "ఎర్రన", "Errana completed the work of Nannaya and Tikkana.", 3],
["vemana", "the Telugu philosopher-poet known for short verses", "వేమన", "Vemana's verses teach simple truths.", 3],
["potana", "the poet who wrote the Andhra Maha Bhagavatam", "పోతన", "Potana's Bhagavatam is written in simple Telugu.", 3],
["vidya", "learning, education", "విద్య", "Vidya is the greatest wealth.", 3],
["pustakam", "book", "పుస్తకం", "The pustakam is on the library shelf.", 2],
["patham", "lesson", "పాఠం", "Today's patham is about rivers.", 2],
["pariksha", "examination", "పరీక్ష", "The pariksha begins next week.", 2],
["sahityam", "literature", "సాహిత్యం", "Telugu sahityam is more than a thousand years old.", 3],
["sanskruti", "culture", "సంస్కృతి", "Festivals are part of our sanskruti.", 3],
["bhasha", "language", "భాష", "Telugu is a sweet bhasha.", 2],
["samajam", "society", "సమాజం", "Education improves the samajam.", 3],
["vijnanam", "science", "విజ్ఞానం", "Vijnanam solves everyday problems.", 3],
["artha", "meaning; also wealth", "అర్థం", "The artha of the word was explained.", 3],
["kavitha", "poem", "కవిత", "She wrote a kavitha on the monsoon.", 2],
["natakam", "drama, play", "నాటకం", "The school staged a natakam.", 3],
["vartha", "news", "వార్త", "The vartha spread through the village.", 2],
["vritti", "profession, occupation", "వృత్తి", "Farming is his vritti.", 3],
["utsavamu", "festival, celebration", "ఉత్సవం", "Sankranti is the biggest utsavamu.", 3],
["prabhutvam", "government", "ప్రభుత్వం", "The prabhutvam built a new school.", 3],
["niti", "policy or moral principle", "నీతి", "Niti guides how leaders govern.", 3],
["chaduvu", "education, study", "చదువు", "Chaduvu opens the door to a better life.", 3]
];
