/* Word Coach Ultra — word bank
   Format: [word, meaning, Telugu gloss, example sentence, level 1-3] */
window.WORD_BANK = [
// ---------- Level 1: everyday power words ----------
["brave","showing courage; not afraid","ధైర్యము","The brave girl spoke in front of the whole school.",1],
["honest","always telling the truth","నిజాయితీ","An honest student returns money he finds.",1],
["kind","friendly and caring to others","దయగల","Be kind to animals and younger children.",1],
["rapid","very fast","వేగవంతమైన","The rapid train reached Hyderabad in one hour.",1],
["silent","making no sound","నిశ్శబ్ద","The library was silent during the exam.",1],
["village","a small group of houses in the countryside","గ్రామం","My grandfather lives in a village near Warangal.",1],
["wisdom","good judgment from knowledge and experience","వివేకము","The old teacher shared her wisdom with us.",1],
["journey","travelling from one place to another","ప్రయాణం","The journey from Hyderabad to Delhi takes one day.",1],
["harvest","gathering crops when they are ready","పంట కొయ్యడం","Farmers celebrate harvest time with songs.",1],
["market","a place where people buy and sell things","మార్కెట్","We buy fresh vegetables at the Sunday market.",1],
["danger","the possibility of harm","ప్రమాదం","The sign warned of danger near the deep river.",1],
["effort","hard work towards a goal","కృషి","Passing the exam needs daily effort.",1],
["habit","something you do regularly without thinking","అలవాటు","Reading one page daily is a good habit.",1],
["insect","a small creature with six legs","కీటకం","A butterfly is a beautiful insect.",1],
["jewel","a precious stone like a diamond or ruby","రత్నం","The queen wore a red jewel in her crown.",1],
["ladder","steps used for climbing up","నిచ్చెన","He climbed the ladder to pick mangoes.",1],
["mentor","a wise person who guides you","మార్గదర్శి","My mentor helps me choose good books.",1],
["narrow","not wide; thin","ఇరుకైన","The narrow lane fits only one bicycle.",1],
["ocean","the vast salt water covering most of Earth","సముద్రం","Whales live deep in the ocean.",1],
["patient","able to wait calmly","సహనం","A patient fisherman waits quietly for hours.",1],
["polite","having good manners","మర్యాదగల","A polite greeting makes teachers happy.",1],
["reward","something given for good work","బహుమతి","The reward for practice is progress.",1],
["shelter","a safe place to stay","ఆశ్రయం","During the storm, the temple gave us shelter.",1],
["talent","a natural skill","ప్రతిభ","Her talent for singing amazed everyone.",1],
["unity","people working together as one","ఐక్యత","In unity, the team won the championship.",1],
["valley","low land between hills or mountains","లోయ","The Kashmir valley is full of flowers.",1],
["weapon","a tool used to fight or defend","ఆయుధం","In the game, a sword is the hero's weapon.",1],
["youth","the time of being young","యవ్వనం","Spend your youth learning useful skills.",1],
["zeal","great energy and enthusiasm","ఉత్సాహం","She practises maths with great zeal.",1],
["anchor","a heavy hook that holds a ship in place","లంగరు","The ship dropped anchor near the port.",1],
["border","the line between two places or countries","సరిహద్దు","Wagah is a famous border ceremony place.",1],
["candle","wax stick that gives light when burning","కొవ్వొత్తి","We lit a candle when the power went off.",1],
["donate","to give something to help others","విరాళమివ్వడం","We donate old books to the village school.",1],
["energy","power to do work","శక్తి","Sleep well to save energy for the match.",1],
["famous","known by many people","ప్రసిద్ధ","Hyderabad is famous for biryani.",1],
["gather","to come together in a group","గుమిగూడడం","Students gather in the ground every morning.",1],
["honour","great respect earned by good actions","గౌరవం","Winning the medal was an honour for our school.",1],
["island","land surrounded by water","దీవి","The Andaman islands are in the Bay of Bengal.",1],
["jungle","a thick forest with wild animals","అడవి","The tiger lives deep in the jungle.",1],
["knight","an armoured warrior of old times","యోధుడు","The knight guarded the castle gate.",1],
// ---------- Level 2: intermediate / exam words ----------
["abundant","present in large quantity","విస్తారమైన","The region has abundant rainfall in July.",2],
["bargain","discussing a price to make it lower","బేరం ఆడడం","My mother can bargain well at the market.",2],
["campaign","planned activities to achieve a goal","ప్రచారము","The school started a clean water campaign.",2],
["decade","a period of ten years","దశాబ్దం","A decade ago, phones had no cameras.",2],
["economy","the system of money and trade of a country","ఆర్థిక వ్యవస్థ","Agriculture supports our economy.",2],
["famine","extreme lack of food over a wide area","కరువు","The famine forced families to migrate.",2],
["genuine","real; not fake","నిజమైన","The shop sells genuine leather bags.",2],
["heritage","valuable traditions passed down generations","వారసత్వము","Charminar is part of our heritage.",2],
["inflation","general rise in prices over time","ద్రవ్యోల్బణం","Inflation makes vegetables costly.",2],
["justice","fair treatment under the law","న్యాయం","The judge gave justice to the poor farmer.",2],
["kingdom","a land ruled by a king or queen","రాజ్యం","The Golconda kingdom was rich in diamonds.",2],
["legislate","to make laws","చట్టం చేయడం","Parliament can legislate for the whole country.",2],
["merchant","a person who buys and sells goods","వ్యాపారి","The merchant travelled with silk and spices.",2],
["nominate","to officially suggest someone for a role","నామినేట్ చేయడం","The class will nominate a leader tomorrow.",2],
["obstacle","something that blocks your way","ఆటంకం","Laziness is an obstacle to success.",2],
["parliament","the group of elected lawmakers","పార్లమెంట్","A new law was discussed in Parliament.",2],
["quantity","an amount or number of something","పరిమాణం","Buy a small quantity of rice first.",2],
["revenue","income earned, especially by government","ఆదాయం","Taxes are the main revenue of the state.",2],
["scarcity","shortage; not enough of something","కొరత","Water scarcity affected the crops.",2],
["treaty","a formal agreement between countries","ఒప్పందం","The two kings signed a peace treaty.",2],
["urban","related to a city","పట్టణ","Hyderabad is a large urban area.",2],
["venture","a risky but hopeful project","సాహస ప్రయత్నం","Opening a tea stall was her first venture.",2],
["welfare","health and happiness of people","సంక్షేమము","The government runs welfare schemes for farmers.",2],
["candidate","a person competing for a post","అభ్యర్థి","Each candidate gave a speech before voting.",2],
["demand","a strong request; need for goods","డిమాండు","There is high demand for mangoes in summer.",2],
["export","to send goods to another country","ఎగుమతి","India exports rice to many countries.",2],
["import","to bring goods from another country","దిగుమతి","We import crude oil for fuel.",2],
["federal","power shared between centre and states","సమాఖ్య","India has a federal system of government.",2],
["majority","more than half","మెజారిటీ","The majority of students passed the test.",2],
["minority","the smaller part of a group","మైనారిటీ","Minority rights are protected by law.",2],
["opinion","what a person thinks or believes","అభిప్రాయం","Everyone shared an opinion about the new rule.",2],
["policy","a plan of action by government or company","విధానం","The new education policy changed our exams.",2],
["protest","to show public disagreement","నిరసన","Farmers held a protest for fair prices.",2],
["summit","a top-level meeting of leaders","శిఖరాగ్ర సమావేశం","Climate was discussed at the world summit.",2],
["budget","a plan of income and spending","బడ్జెట్","Our family budget saves money each month.",2],
["credit","buying now and paying later; praise","రుణము","The bank gave credit to the young farmer.",2],
["deposit","money kept safely in a bank","డిపాజిట్","She made a deposit into her savings account.",2],
["fund","money collected for a purpose","నిధి","The class collected a fund for the picnic.",2],
["ledger","a book recording money in and out","కాయితం, ఖాతా పుస్తకం","The shopkeeper writes daily sales in a ledger.",2],
["audit","an official check of accounts","తనిఖీ","An audit found no mistakes in the office accounts.",2],
// ---------- Level 3: advanced / competitive ----------
["amendment","a formal change to a law","సవరణ","The amendment improved the education act.",3],
["arbitrary","based on whim, not reason","అన్యాయమైన","An arbitrary decision confused the workers.",3],
["bureaucracy","a system of government offices and officials","అధికార వర్గం","Bureaucracy can make approvals slow.",3],
["coalition","parties joining to form a government","సంకీర్ణం","A coalition government was formed after elections.",3],
["commerce","buying and selling on a large scale","వాణిజ్యం","Chambers of commerce support trade.",3],
["constitution","the supreme law of a country","రాజ్యాంగం","Our constitution gives us fundamental rights.",3],
["deficit","the amount by which spending exceeds income","లొట్టు","The budget deficit worried the minister.",3],
["democracy","rule by the people through elections","ప్రజాస్వామ్యం","India is the world's largest democracy.",3],
["diplomacy","skillful handling of relations between nations","రాజనీతి, కూతనీతి","War was avoided through careful diplomacy.",3],
["entrepreneur","a person who starts and runs a business","పారిశ్రామికవేత్త, యజమాని","The young entrepreneur opened two shops.",3],
["fiscal","related to government money and taxes","ఆర్థిక","The fiscal year in India ends in March.",3],
["franchise","the right to vote; a licensed business branch","ఓటు హక్కు","Universal adult franchise began in 1950.",3],
["globalisation","worldwide connection of trade and culture","ప్రపంచీకరణం","Globalisation brought foreign brands to India.",3],
["governance","the way a state is managed and ruled","పాలన","Good governance builds public trust.",3],
["impeachment","formal charge against a top official","మహాభియోగం","Impeachment is a rare and serious process.",3],
["infrastructure","basic systems like roads, power, water","మౌలిక సదుపాయాలు","Better infrastructure attracts new industries.",3],
["investment","money put in to gain profit later","పెట్టుబడి","Her small investment grew into a workshop.",3],
["judiciary","the system of courts and judges","న్యాయవ్యవస్థ","An independent judiciary protects citizens.",3],
["liability","a legal responsibility or debt","బాధ్యత","The company accepted liability for the damage.",3],
["monopoly","single control of a market by one seller","ఏకస్వామ్యం","A monopoly can raise prices unfairly.",3],
["negotiation","discussion aimed at reaching agreement","చర్చలు","The negotiation ended the long dispute.",3],
["ordinance","a temporary law by the executive","ఆర్డినెన్స్","An ordinance was issued when Parliament was closed.",3],
["privatisation","transferring state business to private owners","ప్రైవేటీకరణం","Privatisation of the airline was debated.",3],
["referendum","a direct vote by all people on one issue","ప్రజాభిప్రాయ సేకరణ","The city held a referendum on the metro plan.",3],
["subsidy","government support that lowers a price","రాయితీ, సబ్సిడీ","Farmers receive a subsidy on fertilizer.",3],
["tariff","a tax on imported goods","సుంకము","A tariff on foreign steel protected local mills.",3],
["tribunal","a special court for specific disputes","ట్రిబ్యునల్, ప్రత్యేక న్యాయస్థానం","The water tribunal settled the river dispute.",3],
["veto","the power to reject a decision","వీటో","The president may use a veto on the bill.",3],
["warrant","a legal paper allowing arrest or search","వారెంట్","The police showed a warrant before searching.",3],
["allegiance","loyalty to a country, leader, or cause","విధేయత","Soldiers swear allegiance to the nation.",3],
["consensus","general agreement by all","సర్వసమ్మతి","The committee reached a consensus after hours.",3],
["delegation","a group representing others","ప్రతినిధి బృందం","A student delegation met the collector.",3],
["embargo","an official ban on trade","వాణిజ్య నిషేధం","The embargo stopped oil sales to the nation.",3],
["fraud","dishonest cheating for gain","మోసం","Bank fraud was reported to the police.",3],
["hierarchy","ranking from highest to lowest","శ్రేణి వ్యవస్థ","The office hierarchy was explained to new staff.",3],
["ideology","a set of political ideas","సిద్ధాంతం","Each party explained its ideology to voters.",3],
["municipal","related to a town or city government","పురపాలక","The municipal corporation repaired the road.",3],
["plebiscite","a direct vote of the people on a key question","ప్రజాభిప్రాయ సేకరణ","A plebiscite decided the region's future.",3],
["ratification","formal approval of an agreement","సమ్మతి, అమోదం","Ratification of the treaty took six months.",3],
["sovereignty","supreme independent power of a state","సార్వభౌమత్వం","The constitution protects national sovereignty.",3]
];
